name: OpenEmu.app

on:
  workflow_dispatch:

jobs:
  build:
    name: Build OpenEmu
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ^15.1
      - name: Download the prebuilt dylib to build MAME Core
        run: ./mamearcade_headless.sh download
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Build OpenEmu + Cores (Extended)
        run: xcodebuild -workspace "OpenEmu.xcworkspace" -scheme "OpenEmu + Cores (Extended)" -configuration Release -sdk macosx -arch x86_64 -derivedDataPath DerivedData
      - name: Remove code signature
        working-directory: ${{ github.workspace }}/DerivedData/Build/Products/Release/
        run: codesign --remove-signature *.{app,oecoreplugin}
      - name: Zip OpenEmu Extended
        working-directory: ${{ github.workspace }}/DerivedData/Build/Products/Release/
        run: zip -y -r OpenEmu-extended.zip OpenEmu.app MAME.oecoreplugin 
      - name: Upload OpenEmu Extended
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: OpenEmu-extended.zip
          path: ${{ github.workspace }}/DerivedData/Build/Products/Release/OpenEmu-extended.zip
